name = "JuMPTutorials"
uuid = "767a2c38-803a-11e9-191e-47b580bc80c9"
authors = ["Arpit Bhatia <arpit16229@iiitd.ac.in>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
